In [ ]:
# Contoh membuat DataFrame sederhana dan operasi dasar
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('HandsOnPertemuan3').getOrCreate()

data = [('James', 'Sales', 3000),
        ('Michael', 'Sales', 4600),
        ('Robert', 'Sales', 4100),
        ('Maria', 'Finance', 3000)]
columns = ['EmployeeName', 'Department', 'Salary']

df = spark.createDataFrame(data, schema=columns)
df.show()

+------------+----------+------+
|EmployeeName|Department|Salary|
+------------+----------+------+
|       James|     Sales|  3000|
|     Michael|     Sales|  4600|
|      Robert|     Sales|  4100|
|       Maria|   Finance|  3000|
+------------+----------+------+

# **Tugas 1**

In [22]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('HandsOnPertemuan3').getOrCreate()

data = [('Michael', 'Manager', 50),
        ('Franklin', 'Sales', 10),
        ('Trevor', 'Security', 5),
        ('Rasyad', 'CEO', 100)]
columns = ['EmployeeName', 'Department', 'Salary (Million)']

df = spark.createDataFrame(data, schema=columns)
df.show()

+------------+----------+----------------+
|EmployeeName|Department|Salary (Million)|
+------------+----------+----------------+
|     Michael|   Manager|              50|
|    Franklin|     Sales|              10|
|      Trevor|  Security|               5|
|      Rasyad|       CEO|             100|
+------------+----------+----------------+

# **Tugas 2**

In [ ]:
print("Select Data:")
df.select('EmployeeName', 'Salary (million)').show()

print("Filtering Data:")
df.filter(df['Salary (million)'] > 50).show()

print("Pengelompokan Data:")
df.groupBy('Department').avg('Salary (million)').show()

Select Data:
+------------+----------------+
|EmployeeName|Salary (million)|
+------------+----------------+
|     Michael|              50|
|    Franklin|              10|
|      Trevor|               5|
|      Rasyad|             100|
+------------+----------------+

Filtering Data:
+------------+----------+----------------+
|EmployeeName|Department|Salary (Million)|
+------------+----------+----------------+
|      Rasyad|       CEO|             100|
+------------+----------+----------------+

Pengelompokan Data:
+----------+---------------------+
|Department|avg(Salary (million))|
+----------+---------------------+
|     Sales|                 10.0|
|   Manager|                 50.0|
|  Security|                  5.0|
|       CEO|                100.0|
+----------+---------------------+

# **Tugas 3**

In [ ]:
print("Bonus:")
df = df.withColumn('Salary Bonus', df['Salary (Million)'] * 0.1)
df.show()

print("Total Compensation:")
df.withColumn('Total Compensation', df['Salary (Million)'] + df['Salary Bonus']).show()

Bonus:
+------------+----------+----------------+------------+
|EmployeeName|Department|Salary (Million)|Salary Bonus|
+------------+----------+----------------+------------+
|     Michael|   Manager|              50|         5.0|
|    Franklin|     Sales|              10|         1.0|
|      Trevor|  Security|               5|         0.5|
|      Rasyad|       CEO|             100|        10.0|
+------------+----------+----------------+------------+

Total Compensation:
+------------+----------+----------------+------------+------------------+
|EmployeeName|Department|Salary (Million)|Salary Bonus|Total Compensation|
+------------+----------+----------------+------------+------------------+
|     Michael|   Manager|              50|         5.0|              55.0|
|    Franklin|     Sales|              10|         1.0|              11.0|
|      Trevor|  Security|               5|         0.5|               5.5|
|      Rasyad|       CEO|             100|        10.0|             110.0|
+------------+----------+----------------+------------+------------------+

# **Tugas 4**

In [ ]:
from pyspark.sql.window import Window
from pyspark.sql import functions as F

windowSpec = Window.partitionBy('Department').orderBy('Salary (Million)')
df.withColumn('Rank', F.rank().over(windowSpec)).show()

+------------+----------+----------------+------------+----+
|EmployeeName|Department|Salary (Million)|Salary Bonus|Rank|
+------------+----------+----------------+------------+----+
|      Rasyad|       CEO|             100|        10.0|   1|
|     Michael|   Manager|              50|         5.0|   1|
|    Franklin|     Sales|              10|         1.0|   1|
|      Trevor|  Security|               5|         0.5|   1|
+------------+----------+----------------+------------+----+

# **Tugas 5**

In [4]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2025.8.3)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [5]:
import opendatasets as od
od.download('https://www.kaggle.com/datasets/emirhantemizkol/grand-theft-auto-online-car-dataset')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: rasyadlw
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/emirhantemizkol/grand-theft-auto-online-car-dataset
Downloading grand-theft-auto-online-car-dataset.zip to ./grand-theft-auto-online-car-dataset

100%|██████████| 24.9k/24.9k [00:00<00:00, 108MB/s]

In [6]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('GTA online cars').getOrCreate()

df = spark.read.csv('grand-theft-auto-online-car-dataset/gta_cars.csv', header=True, inferSchema=True)
df.show(35)

+---+----------------+-------+-------------------------------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------------+--------------------+
|_c0|           Model|   Type|Vehicle class(GTA V/GTA Online)|    Vehicle type|          Body style|            Capacity|          Appears in|        Manufacturer|               Price|      Variant(s)|  Similar vehicle(s)|
+---+----------------+-------+-------------------------------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------------+--------------------+
|  0|             BR8|VEHICLE|                     Open Wheel|        Race car|Single seat formu...|          1 (driver)|Grand Theft Auto ...|          Benefactor|$3,400,000 #(Lege...|               0|         DR1#PR4#R88|
|  1|             DR1|VEHICLE|                     Open Wheel|        Race car| Single seat IndyCar|          1 (driver)|Grand Theft Auto ...|            Declasse|$2,997,000 #(Lege...|               0|         BR8#PR4#R88|
|  2|             PR4|VEHICLE|                     Open Wheel|        Race car|Single seat formu...|          1 (driver)|Grand Theft Auto ...|Progen#Dinka (Eng...|$3,515,000 #(Lege...|               0|R88#BR8#DR1#F1#Fe...|
|  3|             R88|VEHICLE|                     Open Wheel|        Race car|Single seat formu...|          1 (driver)|Grand Theft Auto ...|              Ocelot|$3,115,000#(Legen...|               0|PR4#BR8#DR1#F1#Fe...|
|  4|             811|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|             Pfister|$1,135,000 (Legen...|               0|      Comet#Comet SR|
|  5|         Autarch|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|            Överflöd|$1,955,000 (Legen...|               0|Emerus#Entity XF#...|
|  6|           Adder|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|            Truffade|$1,000,000 (Legen...|               0|          Nero#Thrax|
|  7|    Banshee 900R|VEHICLE|                          Super|    Civilian car|2-door wide-body car|2 (driver and pas...|Grand Theft Auto ...|             Bravado|$565,000 (Convers...|               0|Banshee#Sultan RS...|
|  8|          Bullet|VEHICLE|                          Super|    Civilian car|Two-door sports c...|2 (driver and pas...|Grand Theft Auto:...| Vapid (HD Universe)|$84,000 (GTA San ...|               0|              Monroe|
|  9|         Cheetah|VEHICLE|                          Super|    Civilian car|2-door sports car...|2 (driver and pas...|Grand Theft Auto ...|Grotti (HD Universe)|$84,000 (GTA San ...|    VCPD Cheetah|Cheetah Classic#T...|
| 10|         Cyclone|VEHICLE|                          Super|    Civilian car|   Electric hypercar|2 (driver and pas...|Grand Theft Auto ...|                Coil|$1,890,000 (Legen...|               0|    Voltic#Khamelion|
| 11|   Deveste Eight|VEHICLE|                          Super|     Concept Car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|            Principe|$1,795,000 (Legen...|               0|X80 Proto#Visione...|
| 12|          Emerus|VEHICLE|                          Super|    Civilian car|            Supercar|2 (driver and pas...|Grand Theft Auto ...|              Progen|$2,750,000 (Legen...|               0| T20#Krieger#Autarch|
| 13|       Entity XF|VEHICLE|                          Super|    Civilian car|           Super car|2 (driver and pas...|Grand Theft Auto ...|            Överflöd|$795,000 (Legenda...|      Entity XXR|      Autarch#Tyrant|
| 14|      Entity XXR|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|            Överflöd|$2,305,000 (Legen...|               0|      Autarch#Tyrant|
| 15|            ETR1|VEHICLE|                          Super|    Civilian car|Two-door enduranc...|2 (driver and pas...|Grand Theft Auto ...|             Emperor|$1,995,000 (Legen...|               0|         Nero Custom|
| 16|           Furia|VEHICLE|                          Super|    Civilian car|   2-door berlinetta|2 (driver and pas...|Grand Theft Auto ...|              Grotti|$2,740,000#$2,055...|               0|Itali RSX#Turismo...|
| 17|             FMJ|VEHICLE|                          Super|    Civilian car|   Two-door supercar|2 (driver and pas...|Grand Theft Auto ...|               Vapid|$1,750,000 (Legen...|               0|              Vagner|
| 18|             GP1|VEHICLE|                          Super|    Civilian car|   Two-door supercar|2 (driver and pas...|Grand Theft Auto ...|              Progen|$1,260,000 (Legen...|               0|               Tyrus|
| 19|        Infernus|VEHICLE|                          Super|    Civilian car|     2-door supercar|2 (driver and pas...|Grand Theft Auto ...|Pegassi (HD Unive...|$1,000 (Auto merc...|               0|Zentorno#Vacca#Re...|
| 20|       Itali GTB|VEHICLE|                          Super|    Civilian car|2-door sports car...|2 (driver and pas...|Grand Theft Auto#...| Progen (GTA Online)|$1,189,000 (GTA O...|Itali GTB Custom|          T20#Taipan|
| 21|Itali GTB Custom|VEHICLE|                          Super|    Civilian car|            Supercar|2 (driver and pas...|Grand Theft Auto ...|              Progen|$495,000 (Convers...|               0|           Itali GTB|
| 22|         Krieger|VEHICLE|                          Super|    Civilian car|            Supercar|2 (driver and pas...|Grand Theft Auto ...|          Benefactor|$2,875,000 (Legen...|               0|XA-21#Vagner#Visi...|
| 23|            Nero|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|            Truffade|$1,440,000 (Benny...|     Nero Custom|         Adder#Thrax|
| 24|     Nero Custom|VEHICLE|                          Super|    Civilian car|         GT hypercar|2 (driver and pas...|Grand Theft Auto ...|            Truffade|$605,000 (Convers...|               0|          Nero#Thrax|
| 25|          Osiris|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|             Pegassi|$1,950,000 #(Lege...|               0|                   0|
| 26|      Penetrator|VEHICLE|                          Super|    Civilian car|Sports car (GTA)#...|2 (driver and pas...|Grand Theft Auto#...|Ocelot (HD Universe)|$880,000 (GTA Onl...|               0|XA-21#Porka (GTA;...|
| 27|           RE-7B|VEHICLE|                          Super|    Civilian car|LMP1 Race Car/ Gr...|2 (driver and pas...|Grand Theft Auto ...|               Annis|$2,475,000 (Legen...|               0|               S80RR|
| 28|          Reaper|VEHICLE|                          Super|    Civilian car|            Hypercar|2 (driver and pas...|Grand Theft Auto ...|             Pegassi|$1,595,000 (Legen...|               0|Vacca#Zentorno#Te...|
| 29|   Rocket Voltic|VEHICLE|                          Super|    Civilian car|     Custom roadster|2 (driver and pas...|Grand Theft Auto ...|                Coil|$3,830,400#$2,880...|               0|Voltic#Oppressor#...|
| 30|           S80RR|VEHICLE|                          Super|      Racing car|Group C Prototype...|          1 (driver)|Grand Theft Auto ...|               Annis|$2,575,000 (Legen...|               0|               RE-7B|
| 31|             SC1|VEHICLE|                          Super|    Civilian car|        2-door coupe|2 (driver and pas...|Grand Theft Auto ...|           Übermacht|$1,603,000 (Legen...|               0|Jester (GTA V)#Re...|
| 32|        Scramjet|VEHICLE|                          Super|  Custom vehicle|   2-door sports car|2 (driver and pas...|Grand Theft Auto ...|            Declasse|$4,628,400#$3,480...|               0|Rocket Voltic#Rui...|
| 33|       Sultan RS|VEHICLE|                          Super|    Civilian car|2-door rally spor...|2 (driver and pas...|Grand Theft Auto ...|               Karin|$795,000 (Convers...|               0|Elegy#Sultan#Eleg...|
| 34|             T20|VEHICLE|                          Super|Civilian vehicle|   Two-door hypercar|2 (driver and pas...|Grand Theft Auto ...|              Progen|$2,200,000#(Legen...|               0|GP1#Tyrus#Itali G...|
+---+----------------+-------+-------------------------------+----------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------------+--------------------+
only showing top 35 rows

In [7]:
df.groupBy('Vehicle class(GTA V/GTA Online)').count().orderBy("Vehicle class(GTA V/GTA Online)", ascending=False).show()

+-------------------------------+-----+
|Vehicle class(GTA V/GTA Online)|count|
+-------------------------------+-----+
|                           Vans|   34|
|                        Utility|   32|
|                          Super|   48|
|                Sports Classics|   45|
|                         Sports|   79|
|                        Service|   12|
|                         Sedans|   32|
|           SUVs (Civilian)#O...|    3|
|                           SUVs|   32|
|                     Open Wheel|    4|
|                       Off-Road|   58|
|                         Muscle|   68|
|                    Motorcycles|   54|
|                       Military|   17|
|                     Industrial|   10|
|                      Emergency|   16|
|                         Cycles|    7|
|                         Coupes|   14|
|                       Compacts|   17|
|                     Commercial|   19|
+-------------------------------+-----+
only showing top 20 rows

In [16]:
df.filter(df.Type == "VEHICLE").groupBy("Manufacturer").count().orderBy("count", ascending=False).show()

+--------------------+-----+
|        Manufacturer|count|
+--------------------+-----+
|               Vapid|   49|
|            Declasse|   31|
|                   0|   30|
|             Bravado|   25|
|          Benefactor|   22|
|             Pegassi|   22|
|Declasse (HD Univ...|   18|
|               Karin|   15|
|Western Motorcycl...|   14|
|              Grotti|   14|
|                 HVY|   12|
|               Dinka|   12|
|          Dewbauchee|   11|
|              Albany|   11|
|                Enus|   11|
| Brute (HD Universe)|   11|
|           Lampadati|   10|
|                  BF|   10|
|            Nagasaki|   10|
|               Annis|    9|
+--------------------+-----+
only showing top 20 rows